### ISSUE TITLE
[PROPOSAL] common properties in `discriminator` form

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#10]
>> For object, there is no reason not to consider discriminator and properties as one form allowing all three keywords, where in case of discriminator, properties and optionalProperties would define shared properties for all mappings - it would also allow to define the schema for tag e.g. string or number as you cannot imply it from the schema.

> Are you suggesting that this "schema":

```json
{
  "properties": { "a": { "type": "string" }},
  "optionalProperties": { "b": { "type": "string" }},
  "discriminator": {
    "tag": "foo",
    "mapping": {
      "v0": { "properties": { "x": { "type": "string" }}},
      "v1": { "properties": { "y": { "type": "string" }}}
    }
  }
}
```

Would be shorthand for:

```json
{
  "discriminator": {
    "tag": "foo",
    "mapping": {
      "v0": {
        "properties": {
          "a": { "type": "string" },
          "x": { "type": "string" }
        },
        "optionalProperties": {
          "b": { "type": "string" }
        }
      },
      "v1": {
        "properties": {
          "a": { "type": "string" },
          "x": { "type": "string" }
        },
        "optionalProperties": {
          "b": { "type": "string" }
        }
      },
    }
  }
}
```

?

>> it would also allow to define the schema for tag e.g. string or number as you cannot imply it from the schema

> I'm not sure I understand what you're saying here.

**Comment by epoberezkin** [comment]
The proposal is to allow optional or required "properties" and optional "optionalProperties" members in `discriminator` form (but keep `properties` and `discriminator` as separate "forms" with the same type `struct` - see #5).

This approach seems better than merging `properties` and `discriminator`, as keeping them separately aligns the meaning of "form" in the spec with the meaning of "form" in meta-schema -  "tag" and "mapping" either both have be present, or both absent, and the current proposed "forms" syntax (#7) does not allow such constraint.

> Are you suggesting that this "schema" ... Would be shorthand for ...

Sort of. It can be as you suggested (but it creates 2-level form precedent, which I don't like tbh - it complicates tooling/form matching), or as in the example below that is a bit more concise. Either way, does it not look better than having to spell out all common properties twice or more?

```json
{
  "tag": "foo",
  "properties": {
     "foo": { "enum": ["v0", "v1"] },
     "a": { "type": "string" }
  },
  "optionalProperties": { "b": { "type": "string" }},
  "mapping": {
    "v0": { "properties": { "x": { "type": "string" }}},
    "v1": { "properties": { "y": { "type": "string" }}}
  }
}
```

>> it would also allow to define the schema for tag e.g. string or number as you cannot imply it from the schema

> I'm not sure I understand what you're saying here.

Currently there is no way to define the required schema/type for property defined in "tag" member. While "string" tags are common (de facto "enum"), the numbers are also used.

The example above with numbers could be (also with "enum" as in #8):

```json
{
  "tag": "version",
  "properties": {
     "version": { "enum": [0, 1], "type": "uint16" },
     "a": { "type": "string" }
  },
  "optionalProperties": { "b": { "type": "string" }},
  "mapping": {
    "0": { "properties": { "x": { "type": "string" }}},
    "1": { "properties": { "y": { "type": "string" }}}
  }
}
```

The spec could, again (#9), require that "properties" MUST be present and to include at least one property - in case of discriminator pattern, the one defined in "tag". Or the spec could make "properties" optional and imply type "string" with the values from "mapping". But it would create some ambiguity in case above - the implied type is "string" but the intended "type" may be some integer type. Probably better to require "properties" and also "require" that the type of tag is explicitly specified as one of the primitive value types (see #5).

**Comment by ucarion** [comment]
> Currently there is no way to define the required schema/type for property defined in "tag" member. While "string" tags are common (de facto "enum"), the numbers are also used.

There is. When you mark a field as being a `tag`, then its value is forced to be one of the keys of `mapping`. This is covered in the spec.

> The spec could, again (#9), require that "properties" MUST be present and to include at least one property - in case of discriminator pattern, the one defined in "tag". Or the spec could make "properties" optional and imply type "string" with the values from "mapping". But it would create some ambiguity in case above - the implied type is "string" but the intended "type" may be some integer type. Probably better to require "properties" and also "require" that the type of tag is explicitly specified as one of the primitive value types (see #5).

I take the opposite approach in the spec. The properties or optionalProperties of a mapping must not mention the `tag`'s value, because its schema is already defined by the `discriminator` itself.

**Comment by epoberezkin** [comment]
I understand that. But how can I then require a specific number type for tag field? Also not having tag in properties anywhere makes it very confusing - you don't see the shape of object..

**Comment by ucarion** [comment]
You cannot use a number type for a tag field. You also can't have compound or nested tags. I deliberately tried to chew off as little as possible.

I agree that it's not ideal that you don't see the shape of the data as clearly. But it also means that you don't have redundant information in the schema. Redundant information is an opportunity for contradictory constraints on the tag.

**Comment by epoberezkin** [comment]
> You cannot use a number type for a tag field.

Do you mean that the spec does not allow it? That is what I am saying - I’ve seen number used as tag, both in JSON schemas and in data structures (e.g. in languages where you have series of constants instead of enum type, and tag data type is a number, and that’s how it’s transmitted). 

Or do you mean that for JSON data modelling it is a bad practice as it is not clear what the number means? The example I offered shows that if the tag is descriptive (e.g. “version” or “build” etc.) tag can be a number without causing confusion.

> You also can't have compound or nested tags. I deliberately tried to chew off as little as possible.

Can you please clarify? I believe you can have nested tags but probably you mean something else? I agree that we don’t want to allow compound values for tags, only primitive.

> I agree that it's not ideal that you don't see the shape of the data as clearly.

It was very confusing for me and I had to think. Most people will be confused. Also the current discriminator pattern in JSON schema needs tag defined as a required property.

> But it also means that you don't have redundant information in the schema. Redundant information is an opportunity for contradictory constraints on the tag.

JDDF allows creating contradictory schemas already, I don’t think that it is possible to avoid creating contradictory schemas in general (see #5 for example, even without proposed changes), we will have to define how such contradictions should be resolved (e.g. by making schema invalid).

From “explicit over implicit” principle having tag required in properties with the type matching the mapping makes it better, particularly for very large schemas where each mapping is large and you don’t see all possible tag values in one place.

So we can say that the tag property MUST be defined as “enum” form with matching set of values - it would massively help schema comprehension for humans.

Quoting LISP preface, “Programs must be written for people to read, and only incidentally for machines to execute.” (http://www.paulgraham.com/quotes.html)

**Comment by ucarion** [comment]
> Do you mean that the spec does not allow it? That is what I am saying - I’ve seen number used as tag, both in JSON schemas and in data structures (e.g. in languages where you have series of constants instead of enum type, and tag data type is a number, and that’s how it’s transmitted).

That's right, I'm saying the spec doesn't allow it. I agree that tags based on numbers are sometimes used. In those cases, I'm thinking JDDF will simply not be able to support a discriminator pattern, and you'll instead have to use the `properties` form.

> Or do you mean that for JSON data modelling it is a bad practice as it is not clear what the number means? The example I offered shows that if the tag is descriptive (e.g. “version” or “build” etc.) tag can be a number without causing confusion.

I'm not saying it's a bad practice. But it is a comparably much rarer practice than using a string.

> Can you please clarify? I believe you can have nested tags but probably you mean something else? I agree that we don’t want to allow compound values for tags, only primitive.

By that, I mean that your tag can only be `version`, not `foo.version`. You can't do a discriminator like this:

```js
{
  "foo": { "version": "v1" }},
  // the rest of the object's shape depends on foo.version
}
```

> It was very confusing for me and I had to think. Most people will be confused. Also the current discriminator pattern in JSON schema needs tag defined as a required property.

I agree it's less than ideal. But again, the alternative is forcing people to over-specify their tag. If JDDF forces you to specify the tag twice, then JDDF is preventing you from having a single source of truth on what your tag is.

Also, you're gonna have slight weirdness as to the shape of the data no matter what. JDDF isn't an [examplotron](http://examplotron.org/)-style schema language. But I do take your point seriously here. I would love for discriminator to have a shape that's more obviously tied to the data it accepts, but I am not excited about losing DRY in the process.

> JDDF allows creating contradictory schemas already

Can you provide an example? Of a valid (according to the spec) but contradictory schema, aka a schema that nothing can satisfy?

> Quoting LISP preface, “Programs must be written for people to read, and only incidentally for machines to execute.” (http://www.paulgraham.com/quotes.html)

Yes. In addition, programs must also be written for people to maintain, and redundancy is a recipe for incorrect, half-baked changes to schemas. And a schema that seems to contradict itself is the antithesis of readability.

JSON Schema suffers immensely from how careful one must be when writing schemas. In JDDF, I've tried to make a language that has much fewer footguns, and one way I've done this is by ensuring you never have to repeat key names or values twice. There's only a single source of truth for each part of the input you're validating.

Again, I'm open to changing discriminator. But I'm quite strongly leaning _against_ any changes why compromise on non-duplication of information.

**Comment by epoberezkin** [comment]
Consider the example when each schema in a union is large:

```json
{
  "tag": "type",
  "mapping": {
    "foo": {
      "properties": {
        "foo1": {},
        "foo2": {},
        "foo3": {},
        "foo4": {},
        "foo5": {},
        "foo6": {},
        "foo7": {},
        "foo8": {},
        "foo9": {},
        "foo10": {},
        "foo11": {},
        "foo12": {},
        "foo13": {},
        "foo14": {},
        "foo15": {},
        "foo16": {},
        "foo17": {},
        "foo18": {},
        "foo19": {},
        "foo20": {},
        "foo21": {},
        "foo22": {},
        "foo23": {},
        "foo24": {},
        "foo25": {},
        "foo26": {},
        "foo27": {},
        "foo28": {},
        "foo29": {},
        "foo30": {},
        "foo31": {},
        "foo32": {},
        "foo33": {},
        "foo34": {},
        "foo35": {},
        "foo36": {},
        "foo37": {},
        "foo38": {},
        "foo39": {},
        "foo40": {},
        "foo41": {},
        "foo42": {},
        "foo43": {},
        "foo44": {},
        "foo45": {},
        "foo46": {},
        "foo47": {},
        "foo48": {},
        "foo49": {},
        "foo50": {}
      }
    },
    "bar": {
      "properties": {
        "bar1": {},
        "bar2": {},
        "bar3": {},
        "bar4": {},
        "bar5": {},
        "bar6": {},
        "bar7": {},
        "bar8": {},
        "bar9": {},
        "bar10": {},
        "bar11": {},
        "bar12": {},
        "bar13": {},
        "bar14": {},
        "bar15": {},
        "bar16": {},
        "bar17": {},
        "bar18": {},
        "bar19": {},
        "bar20": {},
        "bar21": {},
        "bar22": {},
        "bar23": {},
        "bar24": {},
        "bar25": {},
        "bar26": {},
        "bar27": {},
        "bar28": {},
        "bar29": {},
        "bar30": {},
        "bar31": {},
        "bar32": {},
        "bar33": {},
        "bar34": {},
        "bar35": {},
        "bar36": {},
        "bar37": {},
        "bar38": {},
        "bar39": {},
        "bar40": {},
        "bar41": {},
        "bar42": {},
        "bar43": {},
        "bar44": {},
        "bar45": {},
        "bar46": {},
        "bar47": {},
        "bar48": {},
        "bar49": {},
        "bar50": {}
      }
    },
    "baz": {
      "properties": {
        "baz1": {},
        "baz2": {},
        "baz3": {},
        "baz4": {},
        "baz5": {},
        "baz6": {},
        "baz7": {},
        "baz8": {},
        "baz9": {},
        "baz10": {},
        "baz11": {},
        "baz12": {},
        "baz13": {},
        "baz14": {},
        "baz15": {},
        "baz16": {},
        "baz17": {},
        "baz18": {},
        "baz19": {},
        "baz20": {},
        "baz21": {},
        "baz22": {},
        "baz23": {},
        "baz24": {},
        "baz25": {},
        "baz26": {},
        "baz27": {},
        "baz28": {},
        "baz29": {},
        "baz30": {},
        "baz31": {},
        "baz32": {},
        "baz33": {},
        "baz34": {},
        "baz35": {},
        "baz36": {},
        "baz37": {},
        "baz38": {},
        "baz39": {},
        "baz40": {},
        "baz41": {},
        "baz42": {},
        "baz43": {},
        "baz44": {},
        "baz45": {},
        "baz46": {},
        "baz47": {},
        "baz48": {},
        "baz49": {},
        "baz50": {}
      }
    }
  }
}
```

It is very difficult to understand what values of the tag are allowed by looking at this schema. Compare with this modified example:

```json
{
  "tag": "type",
  "properties": {
    "type": {"enum": ["foo", "bar", "baz"]}
  },
  "mapping": {
    "foo": {
      "properties": {
        "foo1": {},
        "foo2": {},
        "foo3": {},
        "foo4": {},
        "foo5": {},
        "foo6": {},
        "foo7": {},
        "foo8": {},
        "foo9": {},
        "foo10": {},
        "foo11": {},
        "foo12": {},
        "foo13": {},
        "foo14": {},
        "foo15": {},
        "foo16": {},
        "foo17": {},
        "foo18": {},
        "foo19": {},
        "foo20": {},
        "foo21": {},
        "foo22": {},
        "foo23": {},
        "foo24": {},
        "foo25": {},
        "foo26": {},
        "foo27": {},
        "foo28": {},
        "foo29": {},
        "foo30": {},
        "foo31": {},
        "foo32": {},
        "foo33": {},
        "foo34": {},
        "foo35": {},
        "foo36": {},
        "foo37": {},
        "foo38": {},
        "foo39": {},
        "foo40": {},
        "foo41": {},
        "foo42": {},
        "foo43": {},
        "foo44": {},
        "foo45": {},
        "foo46": {},
        "foo47": {},
        "foo48": {},
        "foo49": {},
        "foo50": {}
      }
    },
    "bar": {
      "properties": {
        "bar1": {},
        "bar2": {},
        "bar3": {},
        "bar4": {},
        "bar5": {},
        "bar6": {},
        "bar7": {},
        "bar8": {},
        "bar9": {},
        "bar10": {},
        "bar11": {},
        "bar12": {},
        "bar13": {},
        "bar14": {},
        "bar15": {},
        "bar16": {},
        "bar17": {},
        "bar18": {},
        "bar19": {},
        "bar20": {},
        "bar21": {},
        "bar22": {},
        "bar23": {},
        "bar24": {},
        "bar25": {},
        "bar26": {},
        "bar27": {},
        "bar28": {},
        "bar29": {},
        "bar30": {},
        "bar31": {},
        "bar32": {},
        "bar33": {},
        "bar34": {},
        "bar35": {},
        "bar36": {},
        "bar37": {},
        "bar38": {},
        "bar39": {},
        "bar40": {},
        "bar41": {},
        "bar42": {},
        "bar43": {},
        "bar44": {},
        "bar45": {},
        "bar46": {},
        "bar47": {},
        "bar48": {},
        "bar49": {},
        "bar50": {}
      }
    },
    "baz": {
      "properties": {
        "baz1": {},
        "baz2": {},
        "baz3": {},
        "baz4": {},
        "baz5": {},
        "baz6": {},
        "baz7": {},
        "baz8": {},
        "baz9": {},
        "baz10": {},
        "baz11": {},
        "baz12": {},
        "baz13": {},
        "baz14": {},
        "baz15": {},
        "baz16": {},
        "baz17": {},
        "baz18": {},
        "baz19": {},
        "baz20": {},
        "baz21": {},
        "baz22": {},
        "baz23": {},
        "baz24": {},
        "baz25": {},
        "baz26": {},
        "baz27": {},
        "baz28": {},
        "baz29": {},
        "baz30": {},
        "baz31": {},
        "baz32": {},
        "baz33": {},
        "baz34": {},
        "baz35": {},
        "baz36": {},
        "baz37": {},
        "baz38": {},
        "baz39": {},
        "baz40": {},
        "baz41": {},
        "baz42": {},
        "baz43": {},
        "baz44": {},
        "baz45": {},
        "baz46": {},
        "baz47": {},
        "baz48": {},
        "baz49": {},
        "baz50": {}
      }
    }
  }
}
```

The second example makes it much easier to manage and to maintain, as not only it makes "tag" property definition visible and explicit in the syntax, it also protects from accidental typos. Obviously, "enum" MUST be consistent with the mapping for the schema to be valid.

I do agree that "tag" property MUST NOT be allowed inside schemas in mapping (as it is currently in the spec, as it may lead to repeated and different definitions), but I think that it MUST be required as "enum" in "properties" member of "discriminator" form - it is not violation of DRY principle, as without it "tag" is simply not explicitly defined - its definition is implied from semantics of "discriminator" form, and is not present in its syntax.

**Comment by ucarion** [comment]
> it is not violation of DRY principle, as without it "tag" is simply not explicitly defined - its definition is implied from semantics of "discriminator" form, and is not present in its syntax.

You can't claim it doesn't, at least a little, go against DRY. You're specifically proposing that tag values have to be stated twice, identically, in the same schema. Instead, you should argue that it's an acceptable small violation of the principle in order to make schemas easier to understand.

I don't consider DRY sacrosanct, but I do think it carries the day here.

With this proposal, to add a new value for `tag`, you gotta add it twice. It complicates the rules of what is and isn't a valid schema, and it's a new hoop you have to jump through whenever you modify a schema.

Under the current design, yes: the values of tag are defined through the structure of the discriminator form. In my view, that's not that big of a deal: it's akin to the structure of the `switch (data.type) { ... }` statement you'll be writing in your code in anyway.

**Comment by epoberezkin** [comment]
> it's akin to the structure of the switch (data.type) { ... } statement you'll be writing in your code in anyway.

data.type would likely be enum type defined elsewhere.

Why do people need enum types at all instead of just using string constants? To have visibility of all possible values in one place. Not having it makes it very difficult to reason about if - you have to hunt through many lines to see all possible values.

So values of tag are indeed present, but there is no tag definition in schema syntax at all - it’s only in semantics.

**Comment by ucarion** [comment]
> So values of tag are indeed present, but there is no tag definition in schema syntax at all - it’s only in semantics.

It's in the syntax, just in a different way than how `enum` does it. And yes, it's "spread out" in the sense that the values are far from one another. I believe that's an acceptable evil, if the alternative is to repeat the values in two different places.

**Comment by epoberezkin** [comment]
Distributed syntax = syntax that is implied from semantics. 

The trade-off here is between pragmatically minimalist approach that leads to schema documents that are easy to understand and maintain and absolutely minimalist approach that saves 1 line in schema file and leads to human errors (e.g. typos and failing to add one of the mappings that is needed). Not sure why it’s ok to have extra 10 lines in implementation code and not ok to have extra 1 line in schema if it helps.

I am cool with not including “type” in properties, because type there is self-evident (and the requirement to include it in JSON Schema to limit data to objects leads to human errors).

In this case it’s the opposite - not requiring to explicitly define the tag as enum would lead to human errors. I am not comfortable to have my schemas without having allowed tag values explicitly listed in one place. Having one line to avoid such errors is extremely low price and it is no more a violation of DRY principle than declaring and using enum type (tag schema/allowed values = declaring, mapping keys = using).

I have a very long history of supporting Ajv users - 1000+ issues. More than half of those issues are JSON Schema issues, not Ajv’s. This made me believe that it’s absolutely critical that the spec to be useful should be strict enough to protect spec users from their mistakes, otherwise, if it is permissive and delegates such protection to tooling, it makes this spec much less useful and more confusing and difficult to adopt.

In addition to having tag declaration in “properties”, “properties” member also provides the place to put properties that are shared across all mappings - it supports DRY.

To summarise, what is your position in relation to:
- “properties” and “optionalProperties” for shared properties. I think it’s useful, but if I were doing the modelling I would consider splitting shared and discriminated properties to different objects. But the challenge is from the existing designs where different definitions of shared properties can happen by mistake (e.g. mistyped enums that are supposed to be the same, but turned out to be different - no linting could catch it as the linter would have to assume that they are different by design or to be very intelligent to guess that maybe it’s just typo). So not having some place for shared properties in schema would lead to both strong violation of DRY and to human errors.
- explicit definition for “tag”. I don’t mind some other syntax to list tag values in one place, but for me it’s a very strong requirement. I am not comfortable using this form without it.
As alternative to having schema for tag property, that may be too permissive and allowing wider range of types than we need for tag, it can be a special member e.g. `"tagValues": ["foo", "bar"]` or `"tagEnum": [1, 2]`.

**Comment by ucarion** [comment]
> The trade-off here is between pragmatically minimalist approach that leads to schema documents that are easy to understand and maintain and absolutely minimalist approach that saves 1 line in schema file and leads to human errors (e.g. typos and failing to add one of the mappings that is needed). Not sure why it’s ok to have extra 10 lines in implementation code and not ok to have extra 1 line in schema if it helps.

In your example, which one is the "pragmatically minimalist", and which one is the "absolutely minimalist"? It seems like you're suggesting that your proposal will lead to fewer mistakes than the current spec's design, because the current design is amenable to "failing to add one of the mappings that is needed".

But if that's your argument, then I think you have it backwards. Failing to add one of the mappings that is needed is more likely to happen if there are two places you need to add every mapping.

> I have a very long history of supporting Ajv users - 1000+ issues. More than half of those issues are JSON Schema issues, not Ajv’s. This made me believe that it’s absolutely critical that the spec to be useful should be strict enough to protect spec users from their mistakes, otherwise, if it is permissive and delegates such protection to tooling, it makes this spec much less useful and more confusing and difficult to adopt.

I'm quite confused with this comment. You're suggesting a proposal that complicates the rules of JDDF -- you're adding more rules, and taking away none. You're also, in the process, introducing new ways to create an invalid schema which implementations will have to check for. Isn't this proposal taking us in the wrong direction?

> “properties” and “optionalProperties” for shared properties [...]

On the fence, leaning toward opposition. I agree that it's likely that many schemas will have mappings that share properties in common. But I'm not sure I'm willing to accept the added complexity to the spec that a mechanism for hoisting shared properties would entail.

In particular, I would like to see more clarity around:

1. What precisely are the rules for the "shared" properties versus the properties in each of the mappings?
2. In particular, Is it OK for the same property to be specified both in the "shared" area and also in a particular mapping?
3. Is there going to be a way to "opt-out" of the common properties, for a particular mapping?

> explicit definition for “tag” [...]

Quite strongly opposed. The explicit definition is there, and I appreciate that it's not to your satisfaction. But I will not accept changes to the spec that require you have to put the same information in two different formats.

**Comment by epoberezkin** [comment]
> In your example, which one is the "pragmatically minimalist", and which one is the "absolutely minimalist"?

**Comment by epoberezkin** [comment]
> In your example, which one is the "pragmatically minimalist", and which one is the "absolutely minimalist"?

The one with explicitly defined tag is more pragmatic I believe

> Failing to add one of the mappings that is needed is more likely to happen if there are two places you need to add every mapping.

While it is more likely that user would fail to add a value in one of the places, it makes it less likely that it won’t be added at all. The spec could require that they match both ways, if we limit tag definition to enum form.

> You're also, in the process, introducing new ways to create an invalid schema which implementations will have to check for. Isn't this proposal taking us in the wrong direction?

This argument has a logical flaw equivalent to the flaw in this argument: “types introduce more ways to write invalid code, complicating languages. Types therefore increase probability of mistakes”. The flaw here come from not differentiating between mistakes that are caught early at the time of writing schema (invalid schema) and mistakes that stay unnoticed (failing to add one of the mappings that won’t be noticed until the data using this mapping gets validated). So instead of catching schema errors at the point of their parsing, they may be caught only in production unless there is test coverage for this particular tag value.

> What precisely are the rules for the "shared" properties versus the properties in each of the mappings?
> In particular, Is it OK for the same property to be specified both in the "shared" area and also in a particular mapping?

They should not be allowed to be overridden in mappings. I assumed a simple version when the property can appear either in shared, or in mapping, but not in both places.

> Is there going to be a way to "opt-out" of the common properties, for a particular mapping?

I don’t think it’s common enough requirement to justify this complication. Again, the proposal was to have “shared” properties - I meant properties with the same name and definition across all mappings.

>> explicit definition for “tag” [...]
> Quite strongly opposed. The explicit definition is there, and I appreciate that it's not to your satisfaction. But I will not accept changes to the spec that require you have to put the same information in two different formats.

I suggest you share this conversation and ask opinions of potential spec users - that can make you reconsider your position. I don’t think this position is aligned with “premise of constituents” - you choose theoretic purity over usability for the end users.

**Comment by epoberezkin** [comment]
> I don’t think it’s common enough requirement to justify this complication. Again, the proposal was to have “shared” properties - I meant properties with the same name and definition across all mappings.

And linters can actually identify such properties and suggest moving them to shared.

**Comment by ucarion** [comment]
Just to update here, I am talking to potential users. I will update later.
