### ISSUE TITLE
[PROPOSAL] ref to root schema

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#12]
Not clear how to define ref to the schema itself?

The only way to do it seems to wrap the whole schema in definition, then ref it, so instead of using simple:

```json
{
  "properties": {
    "value": {}
  },
  "optionalProperties": {
    "next": {"ref": "self/whatever"},
  }
}
```

One would have to use

```json
{
  "ref": "list",
  "definitions": {
    "list": {
      "properties": {
        "value": {}
      },
      "optionalProperties": {
        "next": {"ref": "list"},
      }
    }
  }
}
```

**Comment by ucarion** [comment]
Yup, you have to do that. I don't see this as a major issue, though?

**Comment by epoberezkin** [comment]
Self-recursive schemas are quite common to be honest. Can't we reserve something for self-referencing? The trick above is very non-obvious and it took me a bit of thinking.

**Comment by epoberezkin** [comment]
e.g. "self" or "root"

**Comment by ucarion** [comment]
Does this not contradict the principle of being explicit? Are we going to make it illegal to have a definition named `root`?

**Comment by epoberezkin** [comment]
It does. Maybe `"ref": ""`?

It makes sense as it’s also a JSON pointer to root?

**Comment by ucarion** [comment]
It's valid (but probably ill-advised) to have a definition named `""`. Also, using an empty string for this use-case seems even more in the direction of being non-explicit.

This feature really seems to me like one we can get away without having.

**Comment by ucarion** [comment]
I'd like to close this proposal. Unless you're saying that this ticket is now tied to #23, and can't be closed until #23 is closed?

**Comment by epoberezkin** [comment]
Just to list all options, self-referencing can be achieved in several ways:

- special value for "ref" - "self", "", or even "#", as a nod to JSON Schema (obviously, without any other stuff)
- external ref with schema ID - tied with #23 indeed
- special form, e.g. `{"selfRef": true}` or something else, maybe even `["self"]`
- wrapping in definitions - looks ugly and non-obvious

Not sure what's the least evil here, but the last seems the worst to me.

**Comment by ucarion** [comment]
Overall, I disagree on the importance of this feature. It's quite possible to work around this limitation, and if it turns out I'm wrong and we really need this feature, we can work out a new keyword to achieve it.
