### ISSUE TITLE
[PROPOSAL] "?" in property name instead of "optionalProperties"

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#13]
Did you consider instead of having "optionalProperties" simply using "?" as the last symbol in the property name?

And if you really want it, it can be made escapable, but nobody would ever need it... clojure allows "?" in function names, but who uses it in data - and spec can explicitly avoid supporting structs with "?" in properties - they are not cross-platform.

So instead of bulky:

```json
{
  "properties": {
    "value": {}
  },
  "optionalProperties": {
    "comment": {},
  }
}
```
one would use:

```json
{
  "properties": {
    "value": {},
    "comment?": {},
  }
}
```
It looks more expressive and consistent with at least some languages.

**Comment by ucarion** [comment]
This is an intriguing proposal, but I think I prefer the explicit `optionalProperties` rather than this comparably hard-to-discover proposal.

**Comment by epoberezkin** [comment]
agreed, explicit over implicit
