### ISSUE TITLE
[PROPOSAL] "number" and "integer" types

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#14]
Partially, for easier migration

- "number": that depending on usage scenario would either generate a type that allows any number (some languages allow) or validate it. SHOULD would be ok. Linter could warn.
- "integer": limited (32/64 bit depending on implementation and platform) or unlimited size Integer. Some languages support it directly, most languages have libraries. SHOULD would be ok. Linter could warn.

**Comment by ucarion** [comment]
> Partially, for easier migration

Migration from what? JSON Schema to JDDF?

**Comment by epoberezkin** [comment]
Yes

**Comment by ucarion** [comment]
Is JSON Schema's `number` not already covered by JDDF's `float64` or `float32`?

Are you suggesting that `integer` would validate for any number with a zero fractional part, without any constraints on its max/min value? If so, what is your reply to this language already in the spec:

https://tools.ietf.org/html/draft-ucarion-jddf-05#appendix-A.1

```
   This document does not allow "int64" or "uint64" as values for the
   JDDF "type" keyword (see Figure 11 and Section 3.3.3).  Such
   hypothetical "int64" or "uint64" types would behave like "int32" or
   "uint32" (respectively), but with the range of values associated with
   64-bit instead of 32-bit integers, that is:

   o  "int64" would accept numbers between -(2**63) and (2**63)-1

   o  "uint64" would accept numbers between 0 and (2**64)-1

   Users of "int64" and "uint64" would likely expect that the full range
   of signed or unsigned 64-bit integers could interoperably be
   transmitted as JSON without loss of precision.  But this assumption
   is likely to be incorrect, for the reasons given in Section 2.2 of
   [RFC7493].

   "int64" and "uint64" likely would have led users to falsely assume
   that the full range of 64-bit integers can be interoperably procesed
   as JSON without loss of precision.  To avoid leading users astray,
   JDDF omits "int64" and "uint64".
```

**Comment by epoberezkin** [comment]
I’ve made a separate comment on int64 - the quoted RFC mentions JS not supporting integers over 32 bits, but is not true anymore - there is BigInt with unlimited integer size (and quite a few other languages have equivalents).

regardless of int64, “integer” can be allowed as unlimited size

“number” - any number type would match it, can be optional support for both validation and code generation

**Comment by ucarion** [comment]
Even in JavaScript, you can't get BigInt out of JSON.parse, at least not by default. So aren't the problems with double-precision floats still relevant?

**Comment by epoberezkin** [comment]
To some extent they are, but custom parsers (or parsing based on JDDF) solve it. It’s just seems that when JSON, JavaScript and lots of other languages support unlimited size Integer, its a shame not to have at least optional support for it in JDDF. I will think more about it.

**Comment by ucarion** [comment]
I had the same opinion going into things, but you'll notice I eventually removed `(u)int64` and even added a section arguing against it. It's hard to convince the IETF to let pass a spec that talks about 64-integers in JSON, when there's an important RFC telling people not to count on it.

I'm worried about ordinary developers not realizing that by counting on double-precision floats in JSON, they're setting themselves up for failure. A more portable solution is to encode the numbers as a string somehow.

**Comment by epoberezkin** [comment]
> It's hard to convince the IETF to let pass a spec that talks about 64-integers in JSON, when there's an important RFC telling people not to count on it.

That is a strong argument. 

> A more portable solution is to encode the numbers as a string somehow.

Can’t we have an extra type(s) for string encoded numbers then? Because as is, it’s not possible to restrict strings to numbers. Probably a separate issue, but is it worth the discussion?

“integer” - it would be great to have it as an alias to int32 - it is also aligned with JavaScript treatment of integers.

“number” - as an alias for float64, to keep things simple.

**Comment by ucarion** [comment]
How do you feel about having those `integer` and `number` aliases being an AJV thing?

**Comment by epoberezkin** [comment]
I arrived to the same conclusion - no need to have them in the spec. I do have some other number type suggestion, but I will open a separate issue
