### ISSUE TITLE
[PROPOSAL] require whitelisting custom keywords in schema

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#16]
Problem:

One of the painful schema problems is to debug typos in keywords. So while custom keywords should be supported, for extensibility, it creates the problem that typos in optional members of forms (e.g. optionalProperties) will be treated as custom. It can be addressed in implementations of course, but it won’t be a high priority feature until it’s in the spec - e.g., I only added it to Ajv v6 after many complaints of the users spending hours looking for typos in large schemas..

Proposal:

Schema authors MUST whitelist all custom keywords used in the schema with some specified syntax. Implementations MUST fail if schema has any custom member of the form that was not whitelisted.

Possible syntaxes:

I can think of two possible options, in both cases using “custom” keyword allowed only at root level:

1. whitelist custom members per form. E.g. custom member can be allowed for “properties” form, but not for ”elements”. it is more robust, clear, and self-documenting, but it is a bit bulky. 

```json

{
  "custom": {
    "properties": ["patternProperties"]
  },
  "properties": {
    "foo": {}
  },
  "patternProperties": {
    "bar.*": {}
  }
}
```

2. Plain array of allowed custom members - while it does not show where they can appear, it still protects from typos and implementations that support them will have to make semantic checking and reject custom members if they appear in the wrong form.

```json

{
  "custom": ["patternProperties"],
  "properties": {
    "foo": {}
  },
  "patternProperties": {
    "bar.*": {}
  }
}
```

Having this array only in implementation options (as in Ajv v6) makes it less interoperable even within the same platform, as each application would have to do whitelisting separately or (miss schema bugs if they allow custom members without whitelisting).

**Comment by ucarion** [comment]
If you're adding custom keywords that introduce new ways of embedding schemas within other schemas (for example, if you were to introduce a custom `patternProperties` keyword), how would a validator which doesn't understand the structure of `patternProperties` know how to validate the correctness of schemas embedded within `patternProperties`?

I assume your answer is "it wouldn't" -- if a validator doesn't know how `patternProperties` works, it would not know what sub-schemas to validate in the value of the `patternProperties` custom keyword.

But if that's the case, then don't we still have interoperability issues? Because schemas which understand `patternProperties` are going to accept _fewer_ schemas than those which don't, since they'll able to be stricter about validation?

**Comment by ucarion** [comment]
Put another way, I'm not entirely convinced this isn't a job better suited for a linter. If AJV v6 does this, then I'd argue that AJV is acting simultaneously as a validator and a linter.

**Comment by epoberezkin** [comment]
> If you're adding custom keywords that introduce new ways of embedding schemas within other schemas (for example, if you were to introduce a custom patternProperties keyword), how would a validator which doesn't understand the structure of patternProperties know how to validate the correctness of schemas embedded within patternProperties?
> I assume your answer is "it wouldn't" -- if a validator doesn't know how patternProperties works, it would not know what sub-schemas to validate in the value of the patternProperties custom keyword.

Correct. It would be validator's concern - if they support patternProperties, they would know to validate keys as regular expressions and values as schemas. That is an additional argument to have meta-schema btw, as it would be easier to define extensions with internal schemas. If the validator does not support patternProperties, they would simply ignore it, but they would know that patternProperties is not a typo - they can warn that the schema is potentially incompatible.

> But if that's the case, then don't we still have interoperability issues? Because schemas which understand patternProperties are going to accept fewer schemas than those which don't, since they'll able to be stricter about validation?

We do, but this is the case with any extensions that the spec allows (see custom keywords).

The only benefit of this proposal is to highlight possible issues with lack of compatibility and also to make sure that typos are not treated as custom keywords.

I do believe JDDF should be strict and do not allow additional members not defined in the spec, unless they are whitelisted somehow - that makes schemas much easier to maintain.

**Comment by epoberezkin** [comment]
> Put another way, I'm not entirely convinced this isn't a job better suited for a linter. If AJV v6 does this, then I'd argue that AJV is acting simultaneously as a validator and a linter.

That is correct. I am suggesting that schemas that linter would highlight are just invalid schemas, making linting mandatory - the permissiveness of JSON Schema is the source of many bugs and mistakes, and I just don't want to reproduce the same problem here.

**Comment by ucarion** [comment]
> The only benefit of this proposal is to highlight possible issues with lack of compatibility and also to make sure that typos are not treated as custom keywords.

This seems like a job for a linter, which checks for misspellings of keywords?

**Comment by epoberezkin** [comment]
The argument here that it is pragmatic to give validator requirement to be a linter. Also, how would linter know what is mis-spelling and what is custom keyword - by some fuzzy comparison? Isn’t it better to just white-list?

**Comment by ucarion** [comment]
Sure, a whitelist is a good approach for finding misspellings. But why is the whitelist better placed in the schema than the linter?

**Comment by epoberezkin** [comment]
Because then the whitelist is schema specific and cross-platform. Equivalent question would be - why do you need to declare dependencies in code locally, rather than globally?

**Comment by ucarion** [comment]
A downside with this approach is that it isn't easy to implement in a lot of languages like Go or Java, where the idiomatic way of mapping JSON to objects is to define a struct/class with properties, and let `encoding/json` or some sort of Java ObjectMapper do the conversion from JSON.

If we added a whitelisting system, such an approach would not work, or would be considerably more annoying. You would need to keep track of all the fields you ignored from the ObjectMapper (this is not always possible or convenient with many JSON implementations), and ensure none of them are missing from the whitelist.

**Comment by ucarion** [comment]
I'm also not very enthused by the idea of adding more stuff which only works at the root level of schemas.

**Comment by epoberezkin** [comment]
> A downside with this approach is that it isn't easy to implement in a lot of languages like Go or Java, where the idiomatic way of mapping JSON to objects is to define a struct/class with properties, and let encoding/json or some sort of Java ObjectMapper do the conversion from JSON.

The fact that it is difficult to parse JSON into some languages is not a valid argument against this proposal, this is a platform specific concern. This proposal is about cross-platform support of custom keywords.

In any case, in Go you won't be able to convert schema into struct anyway as JSON properties are case insensitive in a standard parser, so if you use it you would allow invalid schemas. So either you'll have to use non-standard parser or to parse into interface{} (which is what JSON Schema go library is doing).

> I'm also not very enthused by the idea of adding more stuff which only works at the root level of schemas.

Not sure how it is related to the real problem that this proposal intends to solve? Do you have a better proposal to solve it in a cross-platform way? Or do you say that the problem of schema maintainability is not something that the spec should be concerned about?

**Comment by ucarion** [comment]
I have put together an alternative way to handle the problem of typos in #38. That proposal also attempts to handle the problem of future extensibility to the spec. Can you take a look at that suggestion, and let me know what you think?
