### ISSUE TITLE
[PROPOSAL] nullable

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#19]
>> no “nullable". It’s a very common use case that the value can be null. I would suggest adding to type form nullable: true

> I'm open to this idea. As it's probably clear, in JDDF I've been trying to get away with as few features as possible. It was my suspicion that optional properties were good enough in many cases, and in other cases you can use an empty schema {}.

> But perhaps I'm wrong, and nullable is not a feature we can live without. My concern is making sure that there is enough idiomatic support serializing/deserializing nullable JSON fields across mainstream languages.

**Comment by epoberezkin** [comment]
`"nullable": true` would be a simple and valuable extension to primitive value (both type and enum).

**Comment by ucarion** [comment]
I'm open to this suggestion. Still thinking through how such a notion could be introduced into the specification -- I'm leaning toward simply copy-pasting `? nullable: bool` into every schema form, and then adding special handling for it in every form.

**Comment by epoberezkin** [comment]
Yes, it makes sense.

**Comment by ucarion** [comment]
@epoberezkin Do you reckon `nullable` should be allowed for the `ref` form? There are some aspects of it that make a nullable+ref combination weird for me:

1. It makes "ref" is no longer basically a copy-paste of a particular definition. It's copy-paste + possibly making the copy-pasted thing nullable.
2. I'm not planning to let people do `{ nullable: false, ref: foo }` and have that cancel out any `nullable: true` in the `foo` definition. So I'm worried this feature would confuse people.
3. JSON Schema, for a very long time, said that `$ref` cancels out any of its sibling keywords, for reasons related primarily to (1). As a prior, I'm inclined to believe that there was some wisdom in JSON Schema's behavior here.

Thoughts? I'm leaning toward saying that `nullable` can't be used alongside a `ref`. It can be used anywhere else though (including a `definition`), although it has no effect on empty-form schemas.

**Comment by epoberezkin** [comment]
> It makes "ref" is no longer basically a copy-paste of a particular definition. It's copy-paste + possibly making the copy-pasted thing nullable.

I don’t have a strong opinion here.

Pros: you can have a standard type defined elsewhere and yet allow null value for it. Potentially easier to define `nullable` in spec - you can define it in one place as a cross-cutting concern rather than separately in each form.
Cons: complicates both schema and data processing - you have to guard as you drill down.

Initially my instinct was to allow it only for primitive values (type, enum).

> I'm not planning to let people do { nullable: false, ref: foo } and have that cancel out any nullable: true in the foo definition. So I'm worried this feature would confuse people.

It indeed gets a bit complicated. With JSON Schema though I consistently had to define 2 defs - one nullable and one not, which was annoying. Maybe we should explicitly prohibit `nullable: false`, rather than to say that the absence of nullable is equivalent to `nullable: false`, as it may create confusion indeed.

> JSON Schema, for a very long time, said that $ref cancels out any of its sibling keywords, for reasons related primarily to (1). As a prior, I'm inclined to believe that there was some wisdom in JSON Schema's behavior here.

That was a very bad decision there that was a source of many schema bugs that went unnoticed - I had to change it Ajv to either throw or use siblings. They’ve changed it finally.

> Thoughts? I'm leaning toward saying that nullable can't be used alongside a ref. It can be used anywhere else though (including a definition), although it has no effect on empty-form schemas.

I am leaning (slightly) towards allowing `nullable: true` everywhere and not allowing `nullable: false` at all. But your approach is also ok.

**Comment by ucarion** [comment]
> I consistently had to define 2 defs - one nullable and one not, which was annoying

Yes, I've had this problem as well. For this reason, I'm leaning back to `ref` alongside `nullable: true` being OK. I'm inclined to explicitly say that `nullable: false` should be considered useless / ignored, "impurity" or whatever be damned. I can call this out explicitly in the spec and test cases.

I'm not super enthused about blocking `nullable: false`. It's hard to do that in Java/Golang, where most deserializers/serializers make it difficult to deal with the old ternary-logic problem of distinguishing `false` vs omission.

I will come to a conclusion about this after making a toy implementation + code generator. It will thus take awhile for me to get back to you on this ticket.

**Comment by epoberezkin** [comment]
I think making “nullable: false” noop is ok, even from purity point of view (rather than prohibiting null that was previously allowed). We just have to say that semantically nullable: false and lack of nullable are equivalent and that nullable: false is not restrictive.

As a side note, it may be worth noting in the spec that none of the standard JDDF keywords are restrictive (unless I am missing something), they are all additive - they define allowed values and each keyword either does nothing or adds to allowed values. This is paradigm change from JSON Schema which is the opposite - each keyword is restrictive. Nullable: false being noop fits this paradigm, so no impurity here.

But custom keywords (however we allow them) can be restrictive.

**Comment by ucarion** [comment]
Sounds good! I will try to flesh out a concrete implementation and see if anything comes up.

As for the question of additive/subtractive, I think that's a question of perspective -- after all, none of the forms are as tolerant as the empty form, right? So in a way, all of the keywords can be seen as taking away from the lenience of the empty form.

But I agree that on the other hand, "nullable" seems to give back some of the possibilities. I see no deep problem with this surface-level inconsistency -- it reflects the fact that JSON Schema is very much "there are tons of keywords, and every keyword is independent and gets ANDed together at the end", whereas JTD is "you have a few set of keywords that are definitely not independent of each other". JSON Schema is kind of a lightweight programming language in JSON, and JTD is kind of a lightweight type system in JSON.
