### ISSUE TITLE
[PROPOSAL] rename "tag" to "discriminator"?

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#20]
The trade-off here is between:

1) "tag" - a shorter name, that is easier to type with lower risk of typos
2) "discriminator" - consistent with form name in JDDF spec and with "discriminator" openAPI schema keyword (that is no-op in 3.0 from validation perspective).

Maybe it's enough to just rename the form in the spec to `"tagged union" (also known as discriminator)` to justify why we call it "tag"?

**Comment by ucarion** [comment]
I am opposed to having the `tag` and `discriminator` keywords having the same name.

I really don't think this is a high-stakes problem. Would you object if we kept this as-is?

**Comment by epoberezkin** [comment]
Happy to keep “tag” as is. It would help to rename the form to “tagged union (also known as discriminator)”

**Comment by ucarion** [comment]
OK, so this ticket is a friend of #33 #34 #35 -- just a renaming of the spec's internal name for a form?

**Comment by epoberezkin** [comment]
Yes. I think it’s better when the form and the main member names follow the same pattern, whatever this is:

- same for both
- form name is data structure name, member name - element in this data structure

The second makes more sense to me, but the spec follows the first with one exception of this form.

**Comment by ucarion** [comment]
The form in the spec is called the "discriminator" form, and the keyword is `discriminator`. I'm confused as to what convention this fails to follow. All of the keywords, without exception, are named after a schema keyword they're related to.

Tag and Mapping are not schema keywords. They're the properties of a discriminator object, but discriminator objects are not schemas.

**Comment by epoberezkin** [comment]
I may be missing something, but I don’t see keyword “discriminator” in the spec - there is only “tag” and “mapping” on the top level of discriminator form.

Your comment reads as if you mean the schema should have a single keyword “discriminator” on top level and “tag” and “mapping” inside it which seems bulkier than needed (and not what I see in the spec)...

**Comment by ucarion** [comment]
I think #36 is the actual issue here. The two examples I have in the syntax section are wrong. The syntax rule is:

```
   ; Note well: the values of mapping are of the properties form.
   discriminator = { tag: tstr, mapping: * tstr => properties }

          Figure 23: CDDL definition of the "discriminator" form
```

And a valid example is:

```
      {
        "discriminator": {
          "tag": "version",
          "mapping": {
            "v1": {
              "properties": {
                "a": { "type": "float32" }
              }
            },
            "v2": {
              "properties": {
                "a": { "type": "string" }
              }
            }
          }
        }
      }
```

**Comment by epoberezkin** [comment]
I see now - I hope my comments now make sense  to you. Did you consider dropping this top level? Why is it needed and not just two properties ? E.g. “discriminator” and “mapping“?

**Comment by epoberezkin** [comment]
That’s the only form with two level syntax and it seems unnecessary tbh - too much extra typing..

**Comment by ucarion** [comment]
Interesting suggestion! I'll ask around about this idea of dropping `mapping` and `tag` (which would rename to `discriminator`) to the top level.
