### ISSUE TITLE
[PROPOSAL] rename additionalProperties

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#21]
>> "strict instance semantics": suggest make it default and recommend that implementations support non-strict mode. What is the reason to create ambiguity here?

> If I understand what you're saying, I came to agree with you on this. Also, "strict" is not a very clear name, so I went with additionalProperties: true/false instead:

> https://tools.ietf.org/html/draft-ucarion-jddf-05#section-3.1

**Comment by epoberezkin** [comment]
Initially I missed the addition of "additionalProperties" (I read JSL first), and then I missed that it is "false" by default, as in JSON Schema the default is "true".

I think there is a high risk of confusion if we use the same name for the member with different semantics in JDDF compared with JSON Schema.

You can argue that it is already the case with "properties" (and you used "RequiredProperties" in go implementation, but for brevity "properties" is better). The difference here is that it is obvious that "properties" are required because:
- that is what people expect. Having required is confusing at first, then it is annoying to maintain.
- there is "optionalProperties" - it is clear that "properties" are required once you see "optional" in the spec.

Also "additionalProperties" is a very controversial keyword in JSON Schema because it is schema level keyword that prevents extensibility (I understand that JDDF does not offer mechanism for extension at the moment).

"strictProperties" with default "true" could be a clearer option having no negative connotations.

**Comment by ucarion** [comment]
What does `strictProperties` _mean_? "Strict" is vague. I initially called it `stictProperties`, but in talking with one of the authors of CDDL, was convinced to be more specific.

`additionalProperties: false` is clearer. It explicitly calls out the sort of thing it's being strict about -- whether additional properties not already mentioned are OK.

Your better argument is about the possible confusion with JSON Schema. But isn't the most common use-case for `additionalProperties` to simply set it to `false`? Which has the same behavior in JTD as it does in JSON Schema?

**Comment by epoberezkin** [comment]
additionalProperties: false has the same behaviour. additionalProperties: true also has the same behaviour. The source of confusion is that JSON Schema default is “true“, JDDF default is “false”. That is why using the same name makes it very confusing.

**Comment by epoberezkin** [comment]
So schema without additionalProperties has different behaviour.

**Comment by ucarion** [comment]
The different defaults is going to be source of confusion no matter what, no? I'm not convinced the naming of the keyword is a big deal.

If you'd like a different name for the property, can you propose such a name? I can say for certain that `strictProperties` will not do, because "strict" means different things to different people.
