### ISSUE TITLE
[PROPOSAL] schema for dictionary keys

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#24]
>> "values": I would allow schema for "keys", particularly if you support "size" in addition to "type". That would allow defining sparse arrays for example or limit the size of the dictionary keys.

> I think the discussion around "size" is relevant here again. It runs into problems of presuming stuff outside of JSON's purview, like how you encode strings. We don't need to solve every problem with JDDF, some things are better handled by other solutions.

**Comment by epoberezkin** [comment]
"keys" can be numbers of specific type, for example in sparse arrays. That would affect the types and tell the parser to treat keys as specific number type.

The proposal is to have optional "keys" member having schema as its value. It would also allow using enum. You can argue that `optionalProperties` with definitions can be used in this case, but it can be very long and repetitive, particularly for a large enum. Some custom constraints on keys can also be supported by validators. "keys" is equivalent to "propertyNames" keyword in JSON Schema.

Example:

schema

```json
{
  "keys": {"type": "uint8"},
  "values": {"type": "string"},
}
```

valid data

```json
{
  "0": "zero",
  "1": "one",
  "2": "two"
}
```

invalid data

```json
{
  "-1": "invalid key",
  "foo": "also invalid key"
}
```

**Comment by ucarion** [comment]
No type system I know of lets you do validation of the keys of maps. You get `Map<String, T>`, and you validate the keys yourself if you want to. I think this is better handled by applications. JTD doesn't need to solve all validation things -- only things you'd reasonably expect a type system to be able to do.

Also, it sounds like you're trying to tie `keys` into code generation by having it generate `map[uint8]XXX` instead of `map[string]XXX`. This sounds complicated.

**Comment by epoberezkin** [comment]
Most type system allow defining type for the keys - string, number, enum. We can say that the acceptable forms for the map keys should be primitive value, I.e. type or enum.

**Comment by epoberezkin** [comment]
> Also, it sounds like you're trying to tie keys into code generation by having it generate map[uint8]XXX instead of map[string]XXX. This sounds complicated.

Yes, map[uint]xxx - it’s quite common.

**Comment by ucarion** [comment]
JSON only gives us string keys. I don't think it's wise to go beyond that.

**Comment by epoberezkin** [comment]
> JSON only gives us string keys.

Correct, but they can represent numbers - I am suggesting approach to validate them and to translate to types - it extends the applicability of the spec. If anything, it may mean that JSON can be a bad media to use for a cross-platform type definition language.

> I don't think it's wise to go beyond that.

Not sure why? It would only be true if `map[uint]xxx` were not needed, which would have been true if sparse arrays and matrices were not common enough, but they are very common in certain applications.

**Comment by ucarion** [comment]
Consider new worlds of complexity we'd be entering with this proposal:

```json
{ "1e1": "foo", "10": "bar" }
```

By sticking to just strings, we can rely on the recommendations of I-JSON to not have to deal with duplicate keys. If you want to introduce a syntax for numbers that's guaranteed not to run into different-chars-same-value problems like `1e1` and `10`, then you're asking the spec to introduce a new syntax for numbers, which is too much to ask for.

In JTD without this feature, you can still parse the keys if you want to, and convert the `map[string]X` to `map[uint]X` or whatever, but JTD/code generated from JTD won't do it for you. And it's up to the application doing the parsing/converting to decide how to deal with what exact syntax of numbers they want to deal with, and with what exact semantics they want to handle duplicate keys, out-of-range values, and other such details.

I'm quite certain I will not accept this feature or any close variation on this feature. For this reason, I'm closing the ticket.
