### ISSUE TITLE
"JDDF's expressiveness" wording

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#29]
line 65:

> JDDF's expressiveness is strategically limited to be no more powerful than what can be expressed in the type systems of mainstream programming languages.

consider re-wording in a more positive language, as is it sounds a bit defensive.

**Comment by ucarion** [comment]
I'm open to this suggestion. Would you prefer:

> JDDF's expressiveness is **intentionally** limited to be no more powerful than what can be expressed in the type systems of mainstream programming languages.

The phrasing here, and its follow-up, is intended to fend off proposals like #28, btw.
