### ISSUE TITLE
"JDDF minimalism" wording

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#30]
line 89:

> "JDDF is intentionally designed as a rather minimal schema language".  Seems unnecessary. Minimal design is a reasonable expectation of any specification at RFC level.

>> Perhaps the phrasing could be better, but I'm not sure how. It's reasonable to expect minimalism, but it's also reasonable to go for a comparatively complex validation system like CDDL. Basically, this is me saying that JDDF is shooting for the low-expressiveness, high-simplicity end of the schema spectrum.

Consider re-wording to be specific of the level of minimalism, as is it sounds defensive

**Comment by ucarion** [comment]
Gotcha. What it sounds like you're saying is: the spec says it's "minimal", but your reply is: "minimal in what way?" -- is that a fair summary?

If so, perhaps I should change "minimal" to "minimally expressive"? I do think there's a solid amount of discussion, in the intro, around the principle of being no more powerful than mainstream type systems. That's what I mean by minimal.
