### ISSUE TITLE
"finite enum" wording

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#31]
>> line 402: "finite". It seems unnecessary to specify the list is "finite". Can you express infinite list in JSON?

> You could have imagined a version of enum that let you "wildcard" strings. In that case, a finite document could talk about an infinite set of strings.

Clarify the wording around "finite" / "infinite" in the spec.

**Comment by ucarion** [comment]
OK, are you suggesting I just drop the word "finite" in that sentence?

**Comment by epoberezkin** [comment]
No, you explained that while the list in enum is finite it defines finite list of values, as opposed to having the finite list of wildcards that can define infinite list of values. The proposal is to clarify that finite applies to the defined data and not to enum itself and maybe explain how it could have been infinite? I guess dropping it is also ok?

**Comment by ucarion** [comment]
This seems like pretty low-stakes stuff to me. Perhaps there's a bit of confusion in the first reading, but surely that evaporates after the first example?

**Comment by epoberezkin** [comment]
Up to you really - it just was a confusing place to read, but it’s ok if you don’t want to change.

**Comment by ucarion** [comment]
Ok, I've captured the concrete proposal in #37. I'll avoid talking about "finite" at all in the spec.
