### ISSUE TITLE
"errors" vs "error indicators" wording

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#32]
>> line 86: "Provide a standardized format for errors" - inconsistent with line 48 (see above)

> This is non-normative language, and in my view doesn't need to use the precise formal language (i.e. "error indicator"). Is it unclear that I'm laying out the requirement that standard error indicators solve?

To me it would seem less confusing if "error indicator" meaning was defined, and then consistently used throughout the spec. Feel free to close if you disagree.

**Comment by epoberezkin** [comment]
also:

> line 93: "JDDF makes code generation and standardized errors easier to implement" - I believe it would still be relatively simple with the most modern languages.

**Comment by ucarion** [comment]
OK, I'm open to using the "error indicator" terminology everywhere. I'll think about what kind of language I can use to explain why I'm saying "error indicator" as opposed to just "error".

> > line 93: "JDDF makes code generation and standardized errors easier to implement" - I believe it would still be relatively simple with the most modern languages.

I think your comment about "still being relatively simple" is really about #28. But I do take the point that I use the different phrasing again.
