### ISSUE TITLE
"values" vs "map" vs "dictionary" form name

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#34]
> line 513: "The seventh form, values". why not to call this form "map"? The member would still be "values", but the form name does not have to be the same (and there are other cases where they are not). Also see "type" proposal (#5)

This is not about the syntax, only about the form name in the spec - should it be "map" or "dictionary" maybe?

**Comment by ucarion** [comment]
See #33. Current convention is to name forms after their keywords. I don't see why this isn't a good enough convention.
