### ISSUE TITLE
Disallow "custom" keywords, introduce "metadata" keyword

### ISSUE THREAD

**Issue by ucarion** [jddf/spec#38]
This issue is a proposal which tries to address two concerns:

1. Making the JDDF specification possible to change in the future. How do make it possible to add new keywords in future versions of the specification, without breaking schemas written against previous versions of the spec?

2. Dealing with typos in hand-written specs. How do we deal with the fact that it's all too easy to accidentally make a typo in spelling "properties", and thus accidentally make a schema do nothing?

This proposal attempts to address both problems by saying:

1. All JDDF forms can have a property called `metadata`. Its value must be an object. The keys can be anything, and the values can be anything.

2. None of the JDDF forms permit "additional" properties. For example, the values form would only allow for the `values` and `metadata` properties; the empty form would only allow for the `metadata` property. Any "additional" properties are errors, and make the schema invalid.

So whereas before, a schema with a typo in `properties` would be interpreted as a schema of the empty form, instead it's an invalid schema. That addresses problem (2) -- typos are now errors.

On the current design of JDDF (without this proposal), it's not going to be possible for us to add new keywords -- there's always the possibility someone is already using the keyword we're using, and so we will run into issues of a new version being incapable of accepting previously-valid schemas, or misinterpreting previously "private" keywords.

By moving custom stuff into `metadata`, we regain the ability to add new keywords to any future version of the spec, addressing problem (1). It seems unwise to try to release a specification into the wild without having any means of later adding anything to the specification.

The greatest downside to this proposal is the added verbosity if someone wants to use a custom keyword. But if it's agreed that problem (1) is a non-negotiable thing to get right, then added verbosity or some other sort of namespacing system (à la "all standard keywords start in `$`") must happen.

**Comment by epoberezkin** [comment]
> The greatest downside to this proposal is the added verbosity if someone wants to use a custom keyword. 

indeed. I assume the suggestion is that any custom stuff should be inside metadata? Or the list of custom keywords should be inside meta-data? Metadata from its name seems intended To be noop from validation/types point of view.

I have one more idea that may address both concerns. I will submit as a separate issue

**Comment by ucarion** [comment]
> I have one more idea that may address both concerns. I will submit as a separate issue

Any progress here?

**Comment by epoberezkin** [comment]
#39

**Comment by epoberezkin** [comment]
Can you clarify “metadata” usage? (My questions above)
