### ISSUE TITLE
[PROPOSAL] Add "items" as alias to "elements"

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#4]
>> elements. Why not “items"? Lots of people would feel more at home and it would simplify migration to JSL - more schemas would just work out of the box.

> I'm sympathetic to the "feel more at home" argument. I chose elements because it seems a more precise word than items. From talking with folks, people unfamiliar with JSON Schema and JDDF seemed to usually guess that items would validate (key, value) pairs of an object, rather than the elements of an array. I don't think any word is going to be precise enough for people to guess its meaning without consulting docs.

> I don't think I agree about "just work out of the box" -- in practice, I suspect very few schemas are going to be compatible with both JSON Schema and JDDF; in other words, I think that ship has sailed.

**Comment by epoberezkin** [comment]
> I'm sympathetic to the "feel more at home" argument. I chose elements because it seems a more precise word than items. From talking with folks, people unfamiliar with JSON Schema and JDDF seemed to usually guess that items would validate (key, value) pairs of an object, rather than the elements of an array. I don't think any word is going to be precise enough for people to guess its meaning without consulting docs.

I agree, but for the the large number of the existing JSON Schema users it will be.

It seems context specific, whether to call array items elements, or to call array elements items... 

If you see here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array you will see "elements" in text and "removedItems" in code. Go and Haskell docs seem more consistent and use elements indeed. But in JavaScript community using "items", particularly in code, is extremely common.

Given that JSON is JavaScript Object Notation, I think we could afford the nod to this community.

Could we compromise on allowing "items" as an alias to "elements" that the implementations SHOULD support? Or even say MAY support? That would simplify adoption and migration a lot and we will also signal to JS community that the universally adopted term is "elements" and not "items". Validators can even optionally warn when "items" is used as non-idiomatic (schema linting).

> I don't think I agree about "just work out of the box" -- in practice, I suspect very few schemas are going to be compatible with both JSON Schema and JDDF; in other words, I think that ship has sailed.

That I completely disagree with. Consider this draft-07 JSON schema:

```json
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "foo": {"type": "string"},
      "bar": {"type": "number"}
    },
    "required": ["foo", "bar"]
  }
}
```

It would be supported out of the box, and the schema linter (if one is available, depending on the options) can warn that:
- array/object types are implied and can/should be removed (see #5) - and obviously alert if the types don't match the form.
- "required" is noop (but matches properties in this case) and should be removed.
- "items" is supported, but non-idiomatic and should be replaced with "elements"

Schemas that have nothing but arrays and objects with all required properties are the most common for JSON schema users - so a lot of schemas will work out of the box.

All the JSON schema semantic keywords (min/max/pattern/etc.) can be supported with custom keyword. So everything will just work and the migration would be super easy.

**Comment by ucarion** [comment]
I really don't think this detail is worth adding a duplicate keyword over. It seems like it complicates implementation too, since it's annoying to have to be able to support two different JSON names ("items", "elements") for the same field (items).

> That I completely disagree with. Consider this draft-07 JSON schema:

But that schema has many issues with respect to JDDF.

* `array` and `object` are not valid types, and type is mutually exclusive with `properties` and `items/elements`. So you're now tying in your proposal in #5 to make your case in this ticket.
* JSON Schema `required` is a no-op in this situation, but very often is a way to split out what JDDF calls `properties` vs `optionalProperties`. There isn't a clean correspondence here.

> Schemas that have nothing but arrays and objects with all required properties are the most common for JSON schema users - so a lot of schemas will work out of the box.

By accident. They'll be in for a nasty surprise pretty quickly though. Better, in my view, to simply allow JSON Schema and JDDF diverge, and use a tool like https://github.com/jddf/json-schema-to-jddf instead.

> All the JSON schema semantic keywords (min/max/pattern/etc.) can be supported with custom keyword. So everything will just work and the migration would be super easy.

Can this argument not be made for many of your proposals?

**Comment by epoberezkin** [comment]
> Better, in my view, to simply allow JSON Schema and JDDF diverge, and use a tool like https://github.com/jddf/json-schema-to-jddf instead.

I do not think that having to use this tool for all schemas is an easy migration path.

The migration plan I would be happy is when some schemas work out of the box because they mean the same in JSON Schema as in JDDF, but with some additional linting that some keywords are unnecessary or non-idiomatic. And schemas would require changes that can be suggested straight away (and users can use the tool).

**Comment by ucarion** [comment]
> I do not think that having to use this tool for all schemas is an easy migration path.

There is no easy migration path possible here. If you tell people they can use JSON Schema schemas as JDDF schemas, they will only be disappointed. Most production users will not be able to use JDDF in place of JSON Schema.

> The migration plan I would be happy is when some schemas work out of the box because they mean the same in JSON Schema as in JDDF, but with some additional linting that some keywords are unnecessary or non-idiomatic. And schemas would require changes that can be suggested straight away (and users can use the tool).

I'm not enthusiastic about changing JDDF to make it compatible with a legacy, ad-hoc solution like JSON Schema. Especially if the proposed changes will introduce multiple ways of doing the same thing, or otherwise make JDDF a less desirable thing to migrate to in the first place.

**Comment by epoberezkin** [comment]
> There is no easy migration path possible here. If you tell people they can use JSON Schema schemas as JDDF schemas, they will only be disappointed. Most production users will not be able to use JDDF in place of JSON Schema.

I plan to make Ajv reject schemas that are not valid schemas in both specs, unless they are explicitly specified as draft-07 (using $schema) - I expect 50% of schemas would pass it if we make some of the proposed changes to JDDF. #5 is critical really.

I guess we need to have a longer conversation on how I plan dual support and transition period, but you really can trust me that I know what I am doing and I know what Ajv users need :)

**Comment by epoberezkin** [comment]
> I'm not enthusiastic about changing JDDF to make it compatible with a legacy, ad-hoc solution like JSON Schema. Especially if the proposed changes will introduce multiple ways of doing the same thing, or otherwise make JDDF a less desirable thing to migrate to in the first place.

This legacy ad-hoc solution has millions of users. Internet is full of RFCs that nobody knows about or uses, apart from a small community that created them.

Let's park this issue for now and discuss #5 to begin with.

**Comment by epoberezkin** [comment]
"items" could be supported by Ajv in JDDF schemas, no need to have it in JDDF spec.
