### ISSUE TITLE
Confirm / clarify spec scope

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#6]
- Cross platform type definitions generation
- Data validation (and efficient code generation for data validation)
- JSON parsing/unmarshalling to correct types (and efficient code generation for JSON unmarshalling)
- JSON stringifying/marshalling (and efficient code generation for JSON marshalling)

What is / isn't in scope and what else?
...

**Comment by ucarion** [comment]
This is covered in the introduction, no?

**Comment by epoberezkin** [comment]
Partially, but I don't think JSON parsing/stringifying part is there.

Sorry - I wrote it when I was thinking what is the best name :)

**Comment by epoberezkin** [comment]
I can create another issue to add JSON parsing/stringifying if you think it is needed and close this one.

**Comment by ucarion** [comment]
Oh, you mean code-generating fast serializer/deserializers?

**Comment by epoberezkin** [comment]
Yes. Fastify uses this approach with JSON schema but it’s only possible for subset of schemas.

**Comment by ucarion** [comment]
I think that's somewhat implied by the idea of code generation in the spec. That said, I am open to explicitly calling out specialized serializer/deserializers in the spec. In languages where there are static types, this is usually redundant with generating the types. But in JS, you're right that it's a distinct use-case for code generation.

**Comment by ucarion** [comment]
Is there anything beyond #15 that we'd like to keep this ticket open for?

**Comment by epoberezkin** [comment]
It’s all covered - thanks
