### ISSUE TITLE
[PROPOSAL] support numbers in "enum"

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#8]
Currently "enum" allows having values with multiple primitive and compound types. It has several problems:

- It can easily lead to mistakes, particularly if compound types are used as "enum" values.
- if strings and numbers are mixed in most cases it is problematic.
- if numbers are used, number type has to be implied, and it may be different from what is actually expected
- should "null" be explicitly added or should it be covered by "nullable" if it is added? See separate proposal.

Possible solutions:

- limit "enum" to numbers and strings only (as there is no real value from boolean enum, unless we want to allow a single boolean value? In this case boolean too).
- require that in case enum values are a number, "type" is required to specify which number type, and in case they are strings, "type" is required to specify whether it's a "string" or "datetime"
- if compounds types would be allowed, then the schema for enum values would be very helpful to avoid mistakes. But the use case for compound enums is very limited and most languages do not support such types - so I think it should not be allowed.

Also see "nullable" proposal

**Comment by ucarion** [comment]
`enum` only allows string values. I'm not sure I understand what's being proposed here.

**Comment by epoberezkin** [comment]
> enum only allows string values. I'm not sure I understand what's being proposed here.

The proposal is to limit enum to primitive types (because it seemed that the spec allows all types, including objects and arrays - possibly I missed)

Also there is a use case for enums of numbers of a certain type.

**Comment by ucarion** [comment]
Are you proposing, then, that `enum` support not only string values, but also number values?

**Comment by epoberezkin** [comment]
Yes. Also, did the spec say it’s strings only?

**Comment by epoberezkin** [comment]
It’s also partially related to #5 - make “type” a member, optional in some cases, and not a form.

**Comment by ucarion** [comment]
> Also, did the spec say it’s strings only?

Yes:

```
3.3.4.  Enum

   The enum form is meant to describe instances whose value must be one
   of a finite, predetermined set of string values.
```

Also, in the syntax:

```
   enum = { enum: [+ tstr] }

               Figure 13: CDDL definition of the "enum" form
```

I'm open to suggestions on how to make this more explicit.

**Comment by ucarion** [comment]
@epoberezkin Are you proposing that we add the ability for `enum` to be either an array of strings, or an array of numbers? If so, that will make deserializing `enum` into many programming languages a pain.

**Comment by epoberezkin** [comment]
> @epoberezkin Are you proposing that we add the ability for enum to be either an array of strings, or an array of numbers?

Yes


> If so, that will make deserializing enum into many programming languages a pain.

It is actually used for bit masks and easy to use in code:

Consider this example:

```json
{
  "properties": {
    "mask": {
      "elements": {
        "type": "uint8",
        "enum": [1, 2, 4, 8, 16, 32, 64, 128]
      } 
    }
  }
}
```

In the code this enum type can be defined as a series of constants (quite a few languages have series of constants as the only alternative to enum anyway):

```javascript
const MASK1 = 1
const MASK2 = 2
const MASK4 = 4
const MASK8 = 8
const MASK16 = 16
const MASK32 = 32
const MASK64 = 64
const MASK128 = 128
```

**Comment by epoberezkin** [comment]
As a side note, we could also consider providing semantic meaning for enum values - it is quite common request in JSON Schema, although I am not a big fan of this idea. The syntax could be (the bits are just randomly assigned in the example):

```json
{
  "properties": {
    "access": {
      "elements": {
        "type": "uint8",
        "enum": [
          {"read": 1},
          {"write": 2},
          {"exec": 4},
          {"dir": 8},
        ]
      } 
    }
  }
}
```

**Comment by ucarion** [comment]
> As a side note, we could also consider providing semantic meaning for enum values - it is quite common request in JSON Schema, although I am not a big fan of this idea. The syntax could be (the bits are just randomly assigned in the example):

I'm rather opposed to this proposal. Documentation, comments, and other such stuff are well-suited for tooling, not validators. I'd prefer to keep the spec mostly about syntax and validation.

The other issue with using a set of numbers for enums is the fact that the generated code, much like the example JavaScript you provide, is rather useless. Is something major lost by not just using `type: uint8` instead? You're always, _always_ going to have validation you do outside of JTD.

**Comment by epoberezkin** [comment]
> I'm rather opposed to this proposal. Documentation, comments, and other such stuff are well-suited for tooling, not validators. I'd prefer to keep the spec mostly about syntax and validation.

Agreed

**Comment by epoberezkin** [comment]
> Is something major lost by not just using type: uint8 instead?

How is it different from using type:string instead of enum with the list of string? The idea here is that only subset of uint8 values is allowed (or any other number type), in the same way as enum with strings limits to subset of all strings.

**Comment by ucarion** [comment]
> How is it different from using type:string instead of enum with the list of string? The idea here is that only subset of uint8 values is allowed (or any other number type), in the same way as enum with strings limits to subset of all strings.

Because strings are amenable to useful code generation for enums, but numbers are not. You end up immediately wanting your proposed variation on `enum`, where you also specify "names" for each of the values.
