### ISSUE TITLE
[PROPOSAL] make "properties" required in `properties` form

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#9]
The lack of "forms" form (#7) in the spec leads to the need to have "properties" optional in `properties` form - it seems quite weird to have `properties` without "properties".

This proposal is to require that "properties" is required and not an empty map.

It would also make meta-schema in #7 much simpler, as you would not have to define additional `optionalProperties` "form" (I understand it's not a separate form in CDDF, but the way forms proposed in #7 the only way to define CDDF schema is to have this "form").

The second part of the proposal is to rename `properties` form to `struct` in the spec (the member  would stay "properties")

**Comment by ucarion** [comment]
> This proposal is to require that "properties" is required and not an empty map.

How would you represent an object where all of the fields are optional?

> The second part of the proposal is to rename properties form to struct in the spec (the member would stay "properties")

I'm not sure I see why the name matters very much. I'm open to it, if you feel it makes the spec easier to read, but this seems like a relatively small matter.

**Comment by epoberezkin** [comment]
> How would you represent an object where all of the fields are optional?

Do you mean that the empty object is also ok? What is the real world use case for it?

In any case you can then have "properties" without members to make it explicit.

**Comment by ucarion** [comment]
So your proposal then becomes to have `properties` always be required if you're gonna have `optionalProperties`? I think I've worked through all the caveats of `properties` being optional in the spec, and in the implementations I've found it adds about ~10 lines of extra code in most languages.

It seems to me that this change is mostly motivated by the "forms" proposal?

**Comment by epoberezkin** [comment]
> I'm not sure I see why the name matters very much. I'm open to it, if you feel it makes the spec easier to read, but this seems like a relatively small matter.

Yes, having form name matching its main member should either be consistent (in which case we should call "discriminator" form "tag") or the form should match data structure name - it would make it clearer for readers. I've created #33, #34 and #35 to track these questions.

> So your proposal then becomes to have properties always be required if you're gonna have optionalProperties

I need to think about it...

It would still help to understand the use case for all properties being optional...

>> How would you represent an object where all of the fields are optional?

> Do you mean that the empty object is also ok? What is the real world use case for it?

I am beginning to miss some equivalent of minProperties here :)

**Comment by ucarion** [comment]
> Do you mean that the empty object is also ok? What is the real world use case for it?

Yes, that's what it means. For example, some systems implement PATCH with update masks, which are variants of a representation where every field is optional.

Given my point here:

> So your proposal then becomes to have properties always be required if you're gonna have optionalProperties? I think I've worked through all the caveats of properties being optional in the spec, and in the implementations I've found it adds about ~10 lines of extra code in most languages.

What is the argument for requiring `properties`? There are use-cases. The implementation doesn't become that much harder. I'm not sure I see a path forward for this proposal, unless you suggest that the newly-created tickets you mentioned are blockers for closing this ticket.

**Comment by epoberezkin** [comment]
Let’s close it - PATCH use case is valid indeed.
